name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          8.x,
          10.x,
          12.x,
          14.x
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true
      - name: Lint with eslint
        run: |
          npm run lint
